version: '3'
services:
  reverse-proxy:
    image: caddy:2
    ports:
      - 4000:80
    volumes:
      - ./reverse-proxy/index.html:/data/index.html
      - ./reverse-proxy/Caddyfile:/etc/caddy/Caddyfile


